framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        default_bus: command.bus
        buses:
            command.bus: ~
            query.bus: ~
            event.bus:
                default_middleware:
                    enabled: true
                    allow_no_handlers: true

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async-cmd: '%env(MESSENGER_TRANSPORT_ASYNC_CMD_DSN)%'
            async-event: '%env(MESSENGER_TRANSPORT_ASYNC_EVENT_DSN)%'
            failed: '%env(MESSENGER_TRANSPORT_FAILED_DSN)%'
            sync: 'sync://'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            'App\Core\TransportContract\Model\NewOutgoingMessageInitiated': async-event
            'App\Core\TransportContract\Model\OutgoingMessageEvent': async-event
            'App\Core\SendMessage\Command\ProcessIncomingMessage': async-cmd

when@test:
    framework:
        messenger:
            transports:
                # replace with your transport name here (e.g., my_transport: 'in-memory://')
                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
                async-cmd: 'in-memory://'
                async-event: 'in-memory://'
