framework:
    default_locale: de
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
          - en
        providers:

when@test:
    framework:
        default_locale: en
